site_name: pinax-comments
pages:
- [index.md, Home]
- [usage.md, Usage]
- [templates.md, Templates]
- [changelog.md, Change Log]
theme: readthedocs
repo_url: https://github.com/pinax/pinax-comments
site_description: "documentation for pinax-comments, a comments app for Django sites"
site_author: "Pinax Team"
markdown_extensions: [admonition]
